version: '3'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"  # Event bus publish
      - "4443:4443"  # Event bus subscribe
      - "4444:4444"  # Selenium Grid UI and WebDriver endpoint
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: "2g"
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: "2g"
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
